### ISSUE TITLE
Sort example raises an exception

### ISSUE THREAD

**Issue by KeenS** [mirah/mirah#344] opened 2015-07-23 01:31 UTC
```
$ cd examples
$ java -jar ../dist/mirahc3.jar sort_closure.mirah
$ java SortClosureTopLevel
unsorted: [9, 5, 2, 6, 8, 5, 0, 3, 6, 1, 8, 3, 6, 4, 7, 5, 0, 8, 5, 6, 7, 2, 3]
Exception in thread "main" java.lang.AbstractMethodError: SortClosureTopLevel$Closure1.compare(Ljava/lang/Object;Ljava/lang/Object;)I
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:324)
	at java.util.TimSort.sort(TimSort.java:189)
	at java.util.TimSort.sort(TimSort.java:173)
	at java.util.Arrays.sort(Arrays.java:659)
	at java.util.Collections.sort(Collections.java:217)
	at SortClosureTopLevel.main(sort_closure.mirah:21)
$ git show
commit efee957bc5c4356107297cdb8b9a4724b7593ed2
Merge: 541b691 0056879
Author: Felix von Ferey <felixvf@users.noreply.github.com>
Date:   Thu Jul 23 02:28:01 2015 +0200

    Merge pull request #336 from felixvf/feature_logging_optimization
    
    Improve compilation speed by factor 1.4.
$ java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
```

**Comment by felixvf** [comment] 2015-07-23 11:09
Thank you for your report.

This indicates at least 2 bugs.

1. Our test suite should have caught this, but hasn't.
2. There seems to be a regression in generating bridge methods.

I'll dig into both of them.

**Comment by felixvf** [comment] 2015-07-23 13:30
The test suite tests exclusively with option "--new-closures", and not without that option. The bug happens only without "--new-closures".

One possibility to fix this would be to drop "old closures" entirely.

**Comment by baroquebobcat** [comment] 2015-07-23 15:08
Hey, does this happen with mirahc2.jar?

**Comment by KeenS** [comment] 2015-07-24 01:22
> Hey, does this happen with mirahc2.jar?

Yes.

```
Exception in thread "main" java.lang.AbstractMethodError: SortClosureTopLevel$Closure1.compare(Ljava/lang/Object;Ljava/lang/Object;)I
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:324)
	at java.util.TimSort.sort(TimSort.java:189)
	at java.util.TimSort.sort(TimSort.java:173)
	at java.util.Arrays.sort(Arrays.java:659)
	at java.util.Collections.sort(Collections.java:217)
	at SortClosureTopLevel.main(sort_closure.mirah:21)
```

**Comment by felixvf** [comment] 2015-07-30 08:40
Hello @KeenS, I believe this is fixed in the current mirah master branch. Could you verify this?

**Comment by KeenS** [comment] 2015-07-30 08:47
@felixvf 
Looks fine.

```mirah
$ java -jar ../dist/mirahc3.jar sort_closure.mirah
* [ClassCompiler] Compiling class SortClosureTopLevel
* [ClassCompiler] Compiling class SortClosureTopLevel$Closure1
$ java SortClosureTopLevel
unsorted: [9, 5, 2, 6, 8, 5, 0, 3, 6, 1, 8, 3, 6, 4, 7, 5, 0, 8, 5, 6, 7, 2, 3]
sorted:   [0, 0, 1, 2, 2, 3, 3, 3, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 8, 8, 8, 9]
```

**Closed** 2015-07-30 08:48 UTC
Labels: closures, regression
