### ISSUE TITLE
Importing a class from a different package fails if macros are involved.

### ISSUE THREAD

**Issue by felixvf** [mirah/mirah#293] opened 2015-03-30 02:34 UTC
Consider these 2 .mirah files:

org/bar/p1/class1.mirah:

      package org.bar.p1
      
      import org.bar.p2.Class2
      # import org.bar.p2.*
      
      class Class1
        macro def foo1
        end
      
        class << self
          def something
            1
          end
          def return_class2
            Class2.something
          end
        end
      end

org/bar/p2/class2.mirah:

      package org.bar.p2
      
      import org.bar.p1.Class1
      # import org.bar.p1.*
      
      class Class2
        macro def foo2
        end
        
        class << self
          def something
            1
          end
          def return_class1
            Class1.something
          end
        end
      end

Compilation currently fails with 

Mirah::MirahError: Cannot find class org.bar.p1.org.bar.p2.Class2

If the import is not

      import org.bar.p2.Class2

but

      import org.bar.p2.*

then compilation succeeds.

If the compilation has succeeded once (and hence the file "org/bar/p2/Class2.class" actually exists), then compilation also succeeds.

**Comment by felixvf** [comment] 2015-03-30 02:42
See pull request https://github.com/mirah/mirah/pull/294

**Comment by baroquebobcat** [comment] 2015-03-30 14:52
Thanks for the reproduction.

**Comment by baroquebobcat** [comment] 2015-04-26 02:35
I figured out what the issue is. The current macro implementation copies the imports from the scope it is defined in. If any of those don't resolve, the macro fails to compile. Since the type is in the second file that hasn't been typed yet, the macro compilation fails.

I'm thinking through a solution.

**Comment by baroquebobcat** [comment] 2015-04-26 04:05
I pushed a fix -- c88f34a2b0334273e24cd991e73c5317d18df201 Since there's not a great way to share code between macros anyway, I feel like it's at least a good first hack at it.

**Closed by baroquebobcat** 2015-04-26 04:05 UTC
